spring:
  application:
    name: user-center
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://43.139.40.182:3306/yupi?useSSL=false
    username: yupi
    password: Hua200113
    #session失效时间
  session:
    timeout: 86400


